--- 
Httptitle:
  class: Httptitle
Control:
  class: Control
  respond_to_private_messages: true
Bash:
  class: Bash
Radio:
  class: Radio
Karaoke:
  class: Karaoke
Exec:
  class: Exec
Geoip:
  class: Geoip
Bans:
  class: Bans
Weather:
  class: Weather
Bitcoin:
  class: Bitcoin
